name: AethosLib
version: '${project.version}'
main: de.aethos.lib.AethosLib
api-version: 1.19
load: STARTUP
authors: [ xXTyraelXx, TheosRee ]
description: Library for Project Ethos
softdepend:
  - PlaceholderAPI
  - WorldGuard