name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Separate Files
        run: |
          mkdir target/artifacts
          mv target/EthosLib.jar target/artifacts/EthosLib.jar

      - name: Upload File
        run: |
          mkdir keys
          touch keys/key.pem
          echo -e "${{secrets.DEPLOY_KEY}}" >> keys/key.pem
          scp -i keys/key.pem -P ${{ secrets.PORT }} target/artifacts/EthosLib.jar ${{ secrets.USERNAME }}@${{ secrets.SERVER }}:${{ secrets.TARGET_DIR }}
          rm -r keys
   

      #- name: SFTP uploader
      #  uses: wangyucode/sftp-upload-action@v2.0.2
      #  with:
      #    host: ${{ secrets.SERVER }}
      #    username: ${{ secrets.USERNAME }}
      #    port: ${{ secrets.PORT }}
      #    password: ${{ secrets.PASSWORD }}
      #    localDir: 'target/artifacts'
      #   remoteDir: ${{ secrets.TARGET_DIR }}


      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            bash ${{ secrets.RESTARTPATH }}
